### ISSUE TITLE
Column Selector widget doesn't hide columns of child rows

### ISSUE THREAD

**Issue by Maaaarc** [Mottie/tablesorter#1120]
Hey there! When I use the widget column selector the widget won't hide columns of child rows. 
I don't have the javascript experience to understand what's going on in the part of this widget, but when I add "!important" to the display property in line 315 of widget-columnSelector.js:
colSel.$style.prop('disabled', false).html( styles.length ? styles.join(',') + ' { display: none !important; }' : '' ); 
then at least some table cells of the child rows disappear, but not all. So if this is actually an issue and not somehow my fault, then I would really appreciate it when someone could fix this.

**Comment by Mottie** [comment]
Hi @Maaaarc!

The column selector should hide child row columns. In a recent update (see #501), `colspan` support was added to `thead` and `tfoot`. I'm not sure why I didn't include `tbody` support.

So, if your child rows do have `colspan`s then use the [`widget-columnSelector.js` file](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-columnSelector.js) I just pushed to the master branch.

**Comment by Maaaarc** [comment]
Hey @Mottie!
First of all: Thanks for that fast response!

So I used your new js file and it kinda made it worse.
One of the child rows with colspan, which is supposed to be hidden after the page is loaded now is suddenly visible. Thats that highlighted row.
![1](https://cloud.githubusercontent.com/assets/10399616/12223876/59b4bf5a-b7e3-11e5-801f-82f3f6264162.jpg)

And the issue is still the same. On this picture I have collapsed the child rows of one row and I'm about to deselect the column "Maßnahme".
![2](https://cloud.githubusercontent.com/assets/10399616/12223887/861990ca-b7e3-11e5-874b-6e17de4a70ad.jpg)

And as you can see on this picture after I deselected the column the child rows are still there.
![3](https://cloud.githubusercontent.com/assets/10399616/12223891/97bd6022-b7e3-11e5-95d6-1a3ef14cce18.jpg)

I don't think that I have modified any of the html to interfere with that widget in a bad way.
Let me know if you want to see some of my javascript stuff.
Thank you very much in advance!

**Comment by Mottie** [comment]
Actually, if you could modify [this demo](https://jsfiddle.net/Mottie/mcn8o3yu/) with an example of the HTML being used, that would help isolate the problem. I think the child row cells might be visible because the column selector is using jQuery `.show()` and `.hide()` on individual cells.

I didn't thoroughly test this last update because I had no idea what the HTML would look like, or what to expect.

**Comment by Maaaarc** [comment]
Ok so I modified the demo and it works like it's supposed to be. [Selector with child rows](https://jsfiddle.net/yvo2psLd/1/).

I think I know what causes the problem I have.
When the child rows get toggled to be visible somehow the td's get the style="display: table-cell" which doesn't happen in the demo even though the java script part which is responsible for showing the child rows is the same. That style prevents the child rows to be hidden when the selector deselects the whole column. I have to debug this. Thanks for your help anyways !

**Comment by Maaaarc** [comment]
However the fix you provided so colspans in tbody get set as well doesn't seem to work properly. The layout of my table gets messed up really bad when I use the new js File.

**Comment by Mottie** [comment]
It would help me fix the problem if I could see the problem :grin:

**Comment by Maaaarc** [comment]
Of course! Here I have some more fancy dancy pictures for you!

That's how it's supposed to look like with child rows collapsed and the js files from the current release:
![4](https://cloud.githubusercontent.com/assets/10399616/12224948/5f140aa8-b7fe-11e5-81fe-5d1a48f8d601.jpg)

That's how it looks like when it finished loading the page with the new js file:
![5](https://cloud.githubusercontent.com/assets/10399616/12224951/7248a9bc-b7fe-11e5-8156-f4b070a35f92.jpg)

Child rows collapsed:
![6](https://cloud.githubusercontent.com/assets/10399616/12224952/7c6d974a-b7fe-11e5-82d7-da9698062d16.jpg)

With collapsed child rows after I selected and deselected some columns a couple of times it seems like it looks like it's supposed to be again.
Now about to deselect the column "Liegenschaft":
![7](https://cloud.githubusercontent.com/assets/10399616/12224961/b110c008-b7fe-11e5-8f47-a6542eb7fcfd.jpg)

After deselection of the column "Liegenschaft" the colspan of the child row gets corrected correctly but the column "Finanzierung" just disappeared as well.
![8](https://cloud.githubusercontent.com/assets/10399616/12224965/f20d06f2-b7fe-11e5-9bef-8136cb39634c.jpg)

I hope this is of help. Let me know when I should modify a demo again.

**Comment by Mottie** [comment]
Yes please modify the demo. The actual HTML (with any sensitive data removed) is the easiest way to troubleshoot this issue.

**Comment by Maaaarc** [comment]
[colspan column selector demo](https://jsfiddle.net/mmfh6fmq/1/)

**Comment by Mottie** [comment]
Ok, it "should" all be fixed now... [updated demo](https://jsfiddle.net/Mottie/mmfh6fmq/2/).

**Comment by Mottie** [comment]
New release available.

**Comment by Maaaarc** [comment]
I can verify that. Everything is working now. Thank you very much for that fast fix!
