### ISSUE TITLE
[widgets scroller WITH filter] Bug when two table following ?

### ISSUE THREAD

**Issue by Frennetix** [Mottie/tablesorter#1240]
Hello,

I have an issue with Tablesorter. When two tables (with filter on) are following, like this :
+---- TABLE 1 -----+
|............................|
+---------------------+
+---- TABLE 2 -----+
|............................|
+---------------------+

When I filter (or order by) on one column I'm getting scrolled top somehow. In my project after filter i'm pushed so far top i can't see my table anymore.
 
I can't put my project here, but I found someone else code with the same issue:
http://jsfiddle.net/Mottie/s4ACj/11/

(scroll to the bottom and click on one column of the second tab)

Is there a workaround ?

Thanks.

**Comment by Mottie** [comment]
Hi @Frennetix!

Wow that must be a really old demo. I think what you want is to set either, or both,  the [`scroller_upAfterSort`](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html#scroller-up-after-sort) or [`scroller_jumpToHeader`](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html#scroller-jump-to-header) option to `false`.

```js
$("table.scroll, table#update").tablesorter({
  theme: 'blue',
  widgets: ["zebra", "filter", "scroller"],
  widgetOptions: {
    scroller_upAfterSort: false,
    scroller_jumpToHeader: false
  }
});
```

I've fixed the code in [that demo](http://jsfiddle.net/Mottie/s4ACj/32/), but it still scrolls a little, so I'm not sure if that'll solve the issue.

**Comment by Frennetix** [comment]
I don't think it worked:
http://jsfiddle.net/s4ACj/33/

Am I doing it correctly ?

**Comment by Mottie** [comment]
The demo you shared is removing the scroller widget. That doesn't need to be done. Please use the demo I updated: http://jsfiddle.net/Mottie/s4ACj/32/

And please clarify what you mean by "the more you scroll the more you go up".

**Comment by Frennetix** [comment]
Hi,

sorry to bother you, but my issue still here.

I'll Create a short video when I come back from work to show you what I got. 

I figured it depends of the resolution of you browser, I'm currently on a 4:3 monitor so the issue is very obvious.

**Comment by Frennetix** [comment]
https://vid.me/dUoq

**Comment by Mottie** [comment]
Ok, now I understand. I have patched the scroller widget in the master branch.

Please try out the changes in [this demo](http://jsfiddle.net/Mottie/s4ACj/34/)

**Comment by Frennetix** [comment]
Works fine :+1:

**Comment by Mottie** [comment]
A new release is now available!
