### ISSUE TITLE
saveSort + pager widget shows all rows on reload

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1525]
Hi,

if both pager and saveSort widget are used the pager shows all rows if that tablesorter already has saved its sorting. You can see it at http://jsfiddle.net/amair/0m4hntg9/

First "run" it, then click on "Header" to sort the table. If you now "run" it again it will show all table rows.

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

That does appear to be a bug... I'll take a look soon.

**Comment by Mottie** [comment]
Fixed in v2.30.0!

**Comment by a-mair** [comment]
The reported problem is gone, but now it won't save sorts.

BTW: Firefox's web developer console reports "Tablesorter Warning! "table.config.saveSort" option not recognized", even if the saveSort widget is loaded.

**Comment by Mottie** [comment]
DOH... ok, I'll look into that.

And `saveSort` is a `widgetOption`, not a core option.

**Comment by Mottie** [comment]
Please check the change in the master branch to see if it fixes the problem. I'll push a new release if it does.

**Comment by a-mair** [comment]
Sorry, but the demo at jsfiddle still doesn't restore sort completely.
You can see it yourself:
First "run" and click "Header" until you get descending sorting (Arrow's looks like "V", session storage holds "[0,1]" for sortList). Now "run" again. Arrow still looks like "V" but it's ascending sorting.
If you now move to the next page then sorting is fine, if you then go back sorting is also fine.

**Comment by Mottie** [comment]
Grrr, yeah that is a problem.
