### ISSUE TITLE
Some issues with scroll widget

### ISSUE THREAD

**Issue by Francks11** [Mottie/tablesorter#906]
Hello @Mottie,

I encounter some issues with scroller widget... It is difficult do it works with all browsers like Internet Explorer > 9, Firefox, Chrome without alignement issues and without any bugs...

Issue n°1

When I add inputs in header, the head columns are not well align with body columns...
You can see a demo here : http://jsfiddle.net/Francks11/oqfq47fc/1/
The problem appears with all browsers.

![capture1](https://cloud.githubusercontent.com/assets/3995851/7607872/2f6a538c-f965-11e4-91fa-195d74a2b90b.png)

Issue n°2

If column data is wrap in several lines, the head columns are not well align with body columns... I have the need that data is wrapped.
You can see a demo here : http://jsfiddle.net/Francks11/oqfq47fc/3/
The problem appears with all browsers.

![capture2](https://cloud.githubusercontent.com/assets/3995851/7608016/6ccd235c-f966-11e4-854e-4d7363b17a1f.png)

Issue n°3

If I update a cell in table and data which grow the cell, the head columns are not well align with body columns...
You can see a demo here http://jsfiddle.net/oqfq47fc/4/
The problem appears with all browsers.

![capture3](https://cloud.githubusercontent.com/assets/3995851/7609713/3ee44708-f976-11e4-88ec-dac3fb771c84.png)

I suppose it is necessary to call a method to refresh header, but which? I have look at documentation and the list of possible methods but which methods is most appropriate?

refreshWidgets 	Refresh the currently applied widgets. Depending on the options, it will completely remove all widgets, then re-initialize the current widgets or just remove all non-current widgets (v2.4; v2.19.0).
updateAll 	Update a column of cells (thead and tbody) (v2.8; v2.19.0).
updateCell 	Update a table cell in the tablesorter data (v2.19.0). 

I have test updateAll method but its works only first time and next time, the rows of tbody disappears...

I have searched through the documentation, but I found not what I need...

Issue n°4

When I add the fixed columns to previous example demo, it works with Chrome but not with Firefox and IE.

You can find demo here : http://jsfiddle.net/oqfq47fc/5/

On chrome : (OK)
![capture4_chrome](https://cloud.githubusercontent.com/assets/3995851/7610028/a5273126-f979-11e4-8f82-195fd53729bd.png)

On firefox : 
![capture4_firefox](https://cloud.githubusercontent.com/assets/3995851/7610044/c5a1ef0e-f979-11e4-9fbe-87355ec376a7.png)

On Internet Explorer :
![capture4_internet_explorer](https://cloud.githubusercontent.com/assets/3995851/7610057/ef47d300-f979-11e4-8c7e-15821d212970.png)

Issue 5 

When we move horizontal scrollbar to right, we can see the moved contents in table border :
![capture5](https://cloud.githubusercontent.com/assets/3995851/7610088/47e98da0-f97a-11e4-8da2-692d88d193eb.png)

![capture6](https://cloud.githubusercontent.com/assets/3995851/7610104/7269a89e-f97a-11e4-812a-ffae2630f3bb.png)

You can find demo here : http://jsfiddle.net/oqfq47fc/5/

Issue 6

When we go on the bottom of table, there is a slight alignment issue :
![capture7](https://cloud.githubusercontent.com/assets/3995851/7610129/bf85cf90-f97a-11e4-86dd-fbf612e72576.png)

Issue 7

I use qTip2 (http://qtip2.com) for tooltip.

Qtip2 works good with table sorter, except if widget scroller is used.

You can find a demo here, without scroller widget : http://jsfiddle.net/oqfq47fc/6/

![capture8](https://cloud.githubusercontent.com/assets/3995851/7610525/dd430d1a-f97d-11e4-8542-3b643a34374c.png)

You can find a demo here, with scroll widget : http://jsfiddle.net/oqfq47fc/7/

Can you help me?

I have looked in the documentation, but forgive me if it's written somewhere and I have not seen.

Thanks.

**Comment by Mottie** [comment]
Hi @Francks11!

Thanks for the extensive descriptions and screenshots. I noticed that all the demos are pointing to the scroller widget from the last version, try changing the link to the scroller widget to this: https://rawgit.com/Mottie/tablesorter/master/js/widgets/widget-scroller.js

This link points to the latest scroller widget code in the master branch which should have fixed some of the above reported issues (I hope).

**Comment by Francks11** [comment]
@Mottie 

Issue 1 

Replaced widget scroller. But it does not fix the bug.
Demo : http://jsfiddle.net/oqfq47fc/14/

Issue 2

Replaced widget scroller. But it does not fix the bug.
Demo : http://jsfiddle.net/oqfq47fc/15/

Issue 3

What is the method to called to refresh only the header?

Issue 4

Replaced widget scroller. But it does not fix the bug.
Demo : http://jsfiddle.net/oqfq47fc/16/

Issue 5

Replaced widget scroller. But it does not fix the bug.
Demo : http://jsfiddle.net/oqfq47fc/17/

Issue 6

Replaced widget scroller. But it does not fix the bug.
Demo : http://jsfiddle.net/oqfq47fc/17/

Issue 7

Replaced widget scroller. But it does not fix the bug.
Demo : http://jsfiddle.net/oqfq47fc/18/

The replacement of widget scroller file has no effect...

Can you help me?

**Comment by Mottie** [comment]
Ok, I'll take a look.

For issue 3, trigger a window resize (I'll look to fix this in the code so it works on update properly) ([demo](http://jsfiddle.net/Mottie/oqfq47fc/19/))

```js
$(window).resize();
```

**Comment by Francks11** [comment]
Mottie thanks for your help for issue 3.

Have you had time to see for other issues?

Thanks.

**Comment by Mottie** [comment]
Sorry, there is too much to do with the scroller widget and I want to get the next version out today.

**Comment by Francks11** [comment]
Okay.

For me, in order, the following issues 4, 1, 2 are blocking and I can't use scroller widget without fixing bugs.

I'll see if I can make my contribution to fix bugs because it's very important to me.

**Comment by Francks11** [comment]
I resolve issue 7.

The bubbles of Qtip2 doesn't appear because I have attached event on table sorter thead which is hidden with scroller widget.

I use this code after table sorter initialisation to do Qtip works :

```
    // init table sorter   
    $('#tvar_1').tablesorter({
        widgets: ['zebra', 'scroller'],
        widgetOptions: {
            scroller_height: 300
        }
    });
    
    // add qTip on header
    var scrollerWrap = jQuery( "#tvar_1" ).closest(".tablesorter-scroller");
    
    if ( scrollerWrap != undefined ) {

        $( '#' + scrollerWrap.attr("id") + ' th[title]').qtip(); 
    }
    else {
        
        $( '#tvar_1 th[title]').qtip(); 
    }
```

You can see a demo here for information : http://jsfiddle.net/oqfq47fc/29/

I now look to fix issue 4, 1, 2 which are very blocking.

:-)

**Comment by Francks11** [comment]
@Mottie,

I work to fixed issue n°1.

I have add following code to fix columns width automatically :

https://github.com/Francks11/tablesorter/commit/c17e1ada05f05ac0b083937b2affb690c38a6b80

Without fix : http://jsfiddle.net/oqfq47fc/35/
With fix : http://jsfiddle.net/oqfq47fc/34/

It doesn't work for the time when fixed columns are presents and when table container has width 100%... and that the columns are fited to available space...

http://jsfiddle.net/oqfq47fc/39/

In your option, it is the good solution to fix the column width? For me is the insurance that hidden thead columns have the same width than the floating thead columns. No?

Can you help me? :-)

**Comment by Mottie** [comment]
To be honest, all the columns line up for me. I am not seeing any issues with Chrome or Firefox. In IE, the header is the same width as the body so there is a scrollbar width of extra scrolling that occurs and that needs to be fixed. All the columns do line up though.

I know you said "The problem appears with all browsers" in the original question... which one did that screen shot come from?

Maybe add some css to set the input widths as a percentage, that would ensure that the inputs in the tbody don't distort the table cells.

**Comment by TheSin-** [comment]
The issue is when using inputs, but it's simple solution of using css to set the input width to 100% and then control the col width with min-width.

**Comment by TheSin-** [comment]
Issue 5 is css, you see it to do cell-spacing, use cell border with a color, right now it's transparent, tell it to use solid white and that will be fixed.

**Comment by Francks11** [comment]
OK thanks for your help. I will try all tomorow and I get you feedback. :-)

**Comment by TheSin-** [comment]
here is Issue 5 working

http://jsfiddle.net/oqfq47fc/42/

**Comment by Francks11** [comment]
Thanks :-). And for issue 4, I think it is input css height issue? (Issue of row alignment on firefox and lE)?

**Comment by Francks11** [comment]
@TheSin- ,

there are line alignment issues on Internet Explorer with your demo :

http://jsfiddle.net/856bzzeL/264/

Scroll, resize and see.

Scroll, line is correct align. I think that there is a refresh problem.

**Comment by Francks11** [comment]
I thought yesterday that the fields were responsible of alignment issue.

Today, I have notice that the responsible is colspan.

Scroller widget doesn't like that header first row contains colspan columns, like you can see here with your demo : http://jsfiddle.net/856bzzeL/308/
 
If I reserve colspan and set to row 2, no alignment issue : http://jsfiddle.net/856bzzeL/309/

**Comment by Francks11** [comment]
I encounter a other bug with all browsers.

If there is not enough content and table is fit to 100% like this demo :

http://jsfiddle.net/856bzzeL/310/

The fixed columns are not well aligned... (appears on window resize)

**Comment by Francks11** [comment]
I tested a few cases and still encounter some bugs, especially with internet explorer 9,10,11 (problem alignment line fixed column).

The scroll widget is also slower than before the update...

I detail as soon as possible with examples.

**Comment by Francks11** [comment]
Hi @Mottie, @TheSin- 

I give my feedback regarding the latest changes.

###### Columns alignment issues (Issue 1, 2 ):

Resolved for Firefox, Chrome, Internet Explorer >= 10.
On **Internet Explorer 9, there is a small aligment issue**, but I can't reproduce it with jsfiddle demo.

###### Row alignment issues (Issue 4) :

Resolved for Firefox, Chrome.
**But not for Internet Explorer**.

You can see with my demo here : http://jsfiddle.net/oqfq47fc/52/

![capture](https://cloud.githubusercontent.com/assets/3995851/7915048/3e330e3e-087b-11e5-8ef7-a844a0ced4a8.png)

###### Issue 5, 6 :

Resolved for all browser.

###### NEW ISSUES :

**Issue 1**

Columns are not well align if fixed columns are not used : http://jsfiddle.net/oqfq47fc/53/

![capture2](https://cloud.githubusercontent.com/assets/3995851/7915499/32cc6b00-087e-11e5-88f3-d75d25117687.png)

If I used fixed columns with same code, its works : http://jsfiddle.net/oqfq47fc/54/

![capture 3](https://cloud.githubusercontent.com/assets/3995851/7915526/5e4434ca-087e-11e5-984f-14e793e88b80.png)

I can reproduce it with your demo : http://jsfiddle.net/856bzzeL/457/

![capture4](https://cloud.githubusercontent.com/assets/3995851/7915597/e5a067f4-087e-11e5-9403-e2af9a7420b6.png)

**Issue 2**

When we use colspan in header, the columns are not well align : http://jsfiddle.net/856bzzeL/459/

![capture5](https://cloud.githubusercontent.com/assets/3995851/7915725/cae10ef4-087f-11e5-872a-36de3b34245b.png)

I have the need to have colspan in header columns.

**Issue 3**

If I use colspan in body, row style is stopped in fixed columns, and not apply to the rest of line : http://jsfiddle.net/oqfq47fc/54/

![capture6](https://cloud.githubusercontent.com/assets/3995851/7915912/e8e14b16-0880-11e5-95fb-9b0853720596.png)


**Issue 4**

Since last change, widget scroller is slower... If I have time, I look into widget scroller code, to determine which code is slow.

That's all for now :-)

**Comment by Mottie** [comment]
Ok, I'll look into the alignment issues.

I think the IE row height issue is because the `colspan` cells are hidden on the scrolling side with nothing to make up the space for it. It would be *very* difficult to make the scroller widget support `colspan`s that span across the fixed column, so if you know you're always going to have two fixed columns, split the `colspan="10"` cell into `colspan="2"` and `colspan="8"` cells.

The question about resizing and the table jumping to the header can be solved by setting the [`scroller_jumpToHeader` option](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#scroller-jump-to-header) to `false`. You might want to also look at the [`scroller_upAfterSort` option](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html#scroller-up-after-sort) if you don't like that behavior either.

**Comment by TheSin-** [comment]
colspan is not support, after a long discussion we thought it would be very odd to start with collapse support in scroller and the rest of TS doesn't even support it yet.  Please refrain from using colspan, and do not file bug reports due to it.

**Comment by Mottie** [comment]
Well, you can use `colspan` in an info-only tbody... anywhere else and the row may not sort as you expect.

**Comment by Francks11** [comment]
And in header?  It can be useful and does not prevent table sort? And other bugs?

**Comment by Francks11** [comment]
What is an info only tbody? Can you provide me a demo please? Thanks :-)

**Comment by TheSin-** [comment]
really? then how do I break it?  lets say cols 1 and 2 are fixed, and you have row 1 as colspan 10, where do I break it in half? How do it? where does the data go? how do I split it?

I think maybe it's more of a design issue, try caption for that info instead, of a title if you are using scroller widget since it won't scroll off the page etc etc.  Heck even tooltips might work depending on the info you are trying to tell the user.

Either way collapse is not support and it does affect it in any cell.

**Comment by Mottie** [comment]
Headers do allow `colspan` and `rowspan`.

The demo you seek in the the documentation, listed under "[Sorting with Multiple Tbodies](http://mottie.github.io/tablesorter/docs/example-multiple-tbodies.html)".

**Comment by TheSin-** [comment]
but if it's in a scroller and you do a fixed col that breaks a span, it will likely break specially in IE.  I've HIGHLY recommend against it.

**Comment by Francks11** [comment]
If I use colspan on header, I set colspan only for not fixed columns. Why it does not work and why its not possible?

**Comment by Francks11** [comment]
Same question for  body?

**Comment by TheSin-** [comment]
use at own risk and do not file tickets for it.  It is UNSUPPORTED so if it works great if you get alignment issues because of it, do not make a ticket.

**Comment by Francks11** [comment]
@TheSin- 

I will help you to improve tablesorter and especially scroller widget. I could well avoid postponing no problem... :-)

Ok I understand it is not supported lol but it is a need that will come back from other people... 

I don't use scroller without fixed columns, but I notice a bug if we use scroller without fixed columns, have you seen this?

http://jsfiddle.net/856bzzeL/457/

**Comment by Mottie** [comment]
Yes, that is the alignment issue I said I would look into... it corrects itself if you resize the window.

**Comment by TheSin-** [comment]
this is a pretty easy fix, I'm working on it, it will only affect no fixed cols.

**Comment by Mottie** [comment]
@Francks11!

TheSin- will yell at me for sharing this, but I actually need to modify what I was saying before.... 

Say you have a table with 9 columns, and you have a info-only `tbody` with a cell set with `colspan="9"`. To make this work with the scroller, and have 2 fixed columns, you'll need to split that one cell into **3 cells**:

* `<td colspan="2">`: visible in the fixed column
* `<td style="display: none">`: because the scroller widget fixed column will hide the 2 fixed cells - so it hides the `colspan="2"` cell and this hidden one - this is because the scroller widget *does not support* `colspan`s!
* `<td colspan="7">`: the `colspan`s still add up to 9 since we really only added that hidden cell because the scroller is hiding the first 2 cells.

```html
<tbody class="tablesorter-infoOnly">
    <tr>
        <td colspan="2">COLSPAN</td>
        <!-- add extra hidden td because the fixed column set to 2
             will hide 2 cells; this hidden cell is a placeholder -->
        <td style="display: none"></td>
        <!-- this cell will show up on the right -->
        <td colspan="7">&nbsp;</td>
    </tr>
</tbody>
```

[Here is a demo](http://jsfiddle.net/1a5yu8yq/23/)

Ok, @TheSin-, this is the last time I'll mention `colspan`s with the scroller widget :stuck_out_tongue_winking_eye:

**Comment by Francks11** [comment]
Thanks a lot @Mottie :-).

Have you try with Internet Explorer?

I see line alignement issue... :-(

oh Internet Explorer...

![capture](https://cloud.githubusercontent.com/assets/3995851/7924393/1021ea34-08bb-11e5-80d0-61ff9636e1ed.png)

Another small effort and it is good :-)

**Comment by TheSin-** [comment]
Hottie just for notes this is the same issue as firefox, I'm willing to bet the div it showing up even though the scrollbars aren't.  again this is just for notes since I can't test this.

**Comment by TheSin-** [comment]
Mottie you Hottie, or at least my computer things so ;)

**Comment by Mottie** [comment]
Your computer needs glasses :stuck_out_tongue:

**Comment by Francks11** [comment]
Hi @Mottie,

I have already try scroller_jumpToHeader or scroller_upAfterSort and it doesn't work for me. You can try here : http://jsfiddle.net/oqfq47fc/57/

If I resize window, the scrollbar go to top...

These options don't work with fixed column. I have try with your demo and I have the same issue : http://jsfiddle.net/856bzzeL/465/

If I remove fixed columns, its works. There is a bug.

I saw you did commit last night. Normal that issue 1 is not resolved? http://jsfiddle.net/oqfq47fc/53/

Normal that I already have alignment issue with your colspan example with Internet Explorer? http://jsfiddle.net/1a5yu8yq/27/ . Not resolved with last commit?

I mention "colspan" for header lol. Have you a workaround to use colspan in header? :-)

**Comment by Mottie** [comment]
The IE issue has not been resolved. I name my commits as to what they fix. If you don't see a commit that says something like fixes IE issue, then it's not fixed.

**Comment by Francks11** [comment]
You referenced your commit for this issue 15 hours ago. That's why I ask this question. And on other commit I saw : fix older IE :-)

**Comment by Mottie** [comment]
I referenced this issue because it has like 8 or 9 issues listed in it; too many, I really just stopped reading them.

**Comment by Francks11** [comment]
I agree with you, it becomes a bit messy... It is difficult to know what is resolved, what is not resolved...

I close this issue and I create individual issue for issue which is not resolved.

Thanks.

**Comment by ilakkuvan** [comment]
alignment issue for chrome also
![1021ea34-08bb-11e5-80d0-61ff9636e1ed](https://cloud.githubusercontent.com/assets/20130611/16343684/27b6d22c-3a56-11e6-999c-93b6b65b49d9.png)

**Comment by ilakkuvan** [comment]
@Mottie  
I am facing alignment issue for chrome also 

![](https://cloud.githubusercontent.com/assets/20130611/16343684/27b6d22c-3a56-11e6-999c-93b6b65b49d9.png)

**Comment by Mottie** [comment]
Hi @ilakkuvan!

Are you seeing the same issue on [this demo page](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html)? Everything is aligned for me, maybe you're using an older version of the widget?

**Comment by ilakkuvan** [comment]
Hi

I am using latest plugin .

**Comment by ilakkuvan** [comment]
@Mottie 
I am same plugin but i am facing probelm

**Comment by Mottie** [comment]
Please modify [this demo](http://jsfiddle.net/Mottie/mqv16pd4/) to demonstrate the problem.

**Comment by ilakkuvan** [comment]
I will check now also same issue 
![untitled-1](https://cloud.githubusercontent.com/assets/20130611/16345067/7ea64110-3a5d-11e6-81c9-8850bd87f0c5.png)

**Comment by ilakkuvan** [comment]
Thanks a lot @Mottie

**Comment by ilakkuvan** [comment]
Working fine @Mottie

**Comment by ilakkuvan** [comment]
@Mottie How to update RTL language

**Comment by Mottie** [comment]
Hi @ilakkuvan!

Two things are required ([demo](https://jsfiddle.net/Mottie/uL8ugxw4/))

* Add a `ts-scroller-rtl` class to the table.

    ```html
    <table class="ts-scroller-rtl">...</table>
    ```

    the reason for the weird naming `ts` instead of `tablesorter` is because with a class name of `tablesorter-scroller-rtl`, the code will think you're trying to add a theme named `scroller-rtl`.

* Whatever element is wrapping the table needs to be set with the css `direction:rtl`. So if your entire page is set, that is fine. If you only want the table to be set as rtl, then set this css on the scroller's wrapper:

    ```css
    .tablesorter-scroller { direction: rtl; }
    ```

I will make this more clear in the documentation.

**Comment by ilakkuvan** [comment]
@Mottie  I am facing performance issue for tablesorter. Please help me

**Comment by ilakkuvan** [comment]
@Mottie I am using 25 column and 500 rows

**Comment by Mottie** [comment]
@ilakkuvan I wouldn't recommend using the scroller widget then; the stickyHeaders widget should work just as well.

**Comment by RajuTicvic** [comment]
@hi friends
 i was using scroller but my table has thead colspan, its not working good 
please help me https://github.com/Mottie/tablesorter/issues/1662#issuecomment-492615599
