### ISSUE TITLE
Help with checkbox selection and the pager widget

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#971]
I'm trying to use a "select all" checkbox, but when using it it's spanning across the pages (starting at page 1) when all I really want is to select all the checkboxes on the *displayed* page. Do you have any suggestions?

**Comment by TheSin-** [comment]
just use the right classes

I don't know them off the top of my head cause I'm working on something else, but it's be like

$('table tr').not('.filtered').find('td input[type=checkbox]').prop('checked', true);

or something like that.

**Comment by Mottie** [comment]
With the pager widget involved, you'll need to use `$('table thead tr:visible')` at the beginning of the code @TheSin- shared.

Actually, I have [this demo](http://jsfiddle.net/abkNM/6163/) which might help.

**Comment by aetna-wsa** [comment]
Perfect!! Thank you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by aetna-wsa** [comment]
Sorry to beat a dead horse, but there is a problem with the code used... it is using nth-child, but I need this to work in IE8. Are there options, there? (Referring to this fiddle: http://jsfiddle.net/abkNM/6163/ )

**Comment by aetna-wsa** [comment]
I'm having other issues. Your example works perfectly and I'm trying to reproduce that the best I can, but when clicking on the 'select all' checkbox, I'm getting this error in Firefox:

TypeError: c.table is undefined
c.table.isUpdating = true;

Obviously IE8 fails, too.

**Comment by Mottie** [comment]
Are you using the [`parser-input-select.js`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) file to deal with the check boxes?

Yes the code in that parser using "nth-child", but it is a [jQuery selector](http://api.jquery.com/nth-child-selector/), added in jQuery v1.1.4, so that shouldn't be a limitation in IE8 - unless you're using that really really really really really old version of jQuery.

I just tried that jsfiddle in Firefox v42.0 without any issues that I could see... what version are you testing on and what steps are you taking to cause the error?

**Comment by aetna-wsa** [comment]
I'm using that file, yes. I'm using FF42 also. Glad that is not an issue, but I still have not resolved my own. Besides that error, I've been able to get it working (partially) in IE, but there is a huge delay in selecting the other checkboxes (only for 130 items.) If you have any insight into that, it would be greatly appreciated.

To get the error in FF, I'm just loading the page with the table using tableSorter. The script runs fine until I click on the 'select all' checkbox -- that is when the error comes up in the Console.

**Comment by Mottie** [comment]
So you're using the exact same code from [this demo](http://jsfiddle.net/abkNM/6163/)? And what version of jQuery are you using?

**Comment by aetna-wsa** [comment]
jQuery 1.9.1

I'm using the same JS code on the page, linking to the same library/widget/add-on files, but my page content and CSS are different (I haven't tried to reproduce the *exact* page as that demo.

**Comment by Mottie** [comment]
Please double check and make sure all of the files are up-to-date... the current release is v2.24.5 (11/10/2015).

**Comment by aetna-wsa** [comment]
jquery.tablesorter.combined.js
/*! tablesorter (FORK) - updated 11-10-2015 (v2.24.5)*/
/* Includes widgets ( storage,uitheme,columns,filter,stickyHeaders,resizable,saveSort ) */

parser-input-select.js
/*! Parser: input & select - updated 10/31/2015 (v2.24.0) *//*

jquery.tablesorter.pager.js
/*!
 * tablesorter (FORK) pager plugin
 * updated 11/10/2015 (v2.24.5)
 */

**Comment by Mottie** [comment]
I don't know what else I can do to help you... I can't duplicate the issue on my end,  and the demo works. If you can duplicate the issue in a jsFiddle, it would really help be troubleshoot. Right now, I'm practicing being a psychic... 

Maybe try disabling all the browser plugins?

**Comment by aetna-wsa** [comment]
Well, now I'm frustrated. I slimmed down the code as much as I could and created a fiddle: http://jsfiddle.net/90j2u0kk/

However, I'm not getting the error. I can't test this in IE8 since jsfiddle is not supported there. What are the possible reasons that putting this in a fiddle rather than my site would allow it to work, but not in the context of my application?

**Comment by aetna-wsa** [comment]
It is still working in IE8 but incredibly slow when selecting all checkboxes. Once I do select all checkboxes, however, I'm getting an error:

Message: 'table' is null or not an object
Line: 1206
URI: http://localhost:9081/PihmsNTMT/js/jquery/tableSorter/jquery.tablesorter.js

I looked at the source for jquery.tablesorter.js and found the "Offending" code:
		updateCell : function( c, cell, resort, callback ) {
			c.table.isUpdating = true;

**Comment by Mottie** [comment]
Ok, so I've now included all the header checkbox code within the `parser-input-select.js` file.... it is currently only available in the master branch. Try out [this demo](http://jsfiddle.net/Mottie/y5dmhybr/).

That error you reported will no longer occur. Please check if the changes improve performance in IE8 as well. Thanks!

**Comment by aetna-wsa** [comment]
You're quite the magician! I have one additional issue: I'm using a dropdown menu at the top of the page to select which results set will be displayed (using the onchange event.) If I 'select all' and change the number of pages displayed, I can see that only those selected on the first screen are checked. However, when clicking 'Next' it is resetting that dropdown select causing the results to go away (i.e. the menu is changing to unselected and defaulting to the original view (with no rows visible.)) Would you know where/how I could track down this problem?

**Comment by aetna-wsa** [comment]
I'm sorry, there is another issue. When reloading the page the select all checkbox is already selected (and won't turn off when clicking it.)

**Comment by Mottie** [comment]
Can you share the dropdown HTML and code being used along with it?

The select all checkbox shouldn't behave in that way, it automatically updates depending on how many visible rows are checked. Reloading the page doesn't really work on jsFiddle, so I guess I could try to duplicate that issue locally. What steps do I need to take?

**Comment by aetna-wsa** [comment]
I'm not really sure it would help. The problem is in one of two places, as I see it: in our codebase somewhere hidden deep or in tableSorter (in that the table refreshes when paging through by clicking on 'Next') If the latter does not occur, I'm assuming I have to figure this out on our side.

Just in case you have some insight, here is a sample of one of the drop down menus controlling the data coming into the table:

```										<select id="selected_client_uid" name="selected_client_uid" class="input130" onchange="getLmCaseManager()">
											<option value="9" selected="selected">ABC Motors</option><option value="201">ABC PEP &amp; WKAB</option><option value="221">ABC Test Company</option><option value="204">ABC Test Company 2</option><option value="224">ABCD Test Company</option><option value="382">Aetna Life Insurance Company</option><option value="383">Aetna Test</option><option value="181">Ascension Health</option><option value="181">Ascension Health</option><option value="8">B &amp; G Manufacturing</option><option value="421">Bek Management</option><option value="11">Build Right Construction</option><option value="12">Canada's Finest Pulp and Paper </option>
											</select>
```
The problem is that there is no issue with actually changing the dropdown menu - in fact, we DO want it to repopulate with the newly selected client. The actual issue is that hitting 'Next' is causing a page refresh that restores the dropdown to its undefined state.
